//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BillDetails
    {
        public int idBill { get; set; }
        public int idProduct { get; set; }
        public int quanTum { get; set; }
    
        public virtual tbl_Bill tbl_Bill { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
