//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_BillDetails = new HashSet<tbl_BillDetails>();
        }
    
        public int idProduct { get; set; }
        public string nameProduct { get; set; }
        public string imageProduct { get; set; }
        public string desProduct { get; set; }
        public Nullable<int> priceProduct { get; set; }
        public Nullable<int> rateProduct { get; set; }
        public Nullable<int> quantum { get; set; }
        public Nullable<bool> status { get; set; }
        public int idCate { get; set; }
        public int idUser { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BillDetails> tbl_BillDetails { get; set; }
    }
}
