//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Bill()
        {
            this.tbl_BillDetails = new HashSet<tbl_BillDetails>();
        }
    
        public int idBill { get; set; }
        public Nullable<System.DateTime> dateCheckin { get; set; }
        public Nullable<System.DateTime> datecheckout { get; set; }
        public Nullable<bool> statusBill { get; set; }
        public int sumPrice { get; set; }
        public int idCustomer { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BillDetails> tbl_BillDetails { get; set; }
    }
}
